config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :generates
  resources :states
  resources :countries
  resources :provinces
  resources :cities
  resources :locations
  resources :genres
  resources :albums
  resources :songs
  resources :artists
  resources :genre_artists
  resources :album_types
  resources :artist_albums
  post 'core/:song_id', to: 'core#show', as: 'core_path'
  get '/main_page/', to: 'main_page#index', as: 'main_page_path'
  get '/genre_artists/:artist_id/add_genres', to: 'genre_artists#add_genres'
  post '/genre_artists/add_genres', to: 'genre_artists#create'
  get '/artists_albums/:artist_id/add_albums', to: 'artists_albums#add_albums'
  post '/artists_albums/add_albums', to: 'artists_albums#create'
  get '/songs/:album_id/add_genres', to: 'songs#add_songs', as: 'add_songs_path'  
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :album_type
  has_and_belongs_to_many :artists
  has_many :songs , dependent: :destroy
  has_many :artist_albums
  has_many :artist , through: :artist_albums
  has_many :genre_albums
  has_many :genres, through: :genre_albums
end

app/models/album_artist.rb
class AlbumArtist < ApplicationRecord
  belongs_to :artist_id
  belongs_to :album_id
end

app/models/album_type.rb
class AlbumType < ApplicationRecord
end

app/models/artist.rb
class Artist < ApplicationRecord
  #validations
  validates :nombre, presence: true
  validates :descripcion, presence: true

  #relations
  belongs_to :location
  belongs_to :state
  has_and_belongs_to_many :albums
  has_many :genre_artists , dependent: :destroy
  has_many :genres , through: :genre_artists, dependent: :destroy
  has_many :songs , through: :albums, dependent: :destroy
end

app/models/city.rb
class City < ApplicationRecord
  #validations
  validates :nombre, presence: true 
  #relations
  belongs_to :province
  has_many :locations , dependent: :destroy

end

app/models/colaboration.rb
class Colaboration < ApplicationRecord
  #validations
  validates :artist_id, presence: true
  validates :song_id, presence: true
  #relations
  belongs_to :artist
  belongs_to :song
end

app/models/country.rb
class Country < ApplicationRecord
	#Validations
	validates :nombre , presence: true
	#Relations
	has_many :provinces , dependent: :destroy
	has_many :locations , dependent: :destroy
end

app/models/generate.rb
class Generate < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
	#validations
  	validates :nombre, presence: true 
  	#relations
	has_many :genre_artists
	has_many :artists ,through: :genre_artists
	has_many :genre_albums
	has_many :albums ,through: :genre_albums
end

app/models/genre_album.rb
class GenreAlbum < ApplicationRecord
  validates :genre_id, presence: true
  validates :album_id, presence: true

  belongs_to :genre
  belongs_to :album
end

app/models/genre_artist.rb
class GenreArtist < ApplicationRecord
  validates :artist_id, presence: true
  validates :genre_id, presence: true

  belongs_to :artist
  belongs_to :genre
end

app/models/location.rb
class Location < ApplicationRecord
  validates :city_id, presence: true
  validates :province_id, presence: true
  validates :country_id, presence: true

  belongs_to :city
  belongs_to :province
  belongs_to :country
end

app/models/province.rb
class Province < ApplicationRecord
  #validations
  validates :nombre, presence: true 
  #relations
  belongs_to :country
  has_many :cities , dependent: :destroy

end

app/models/song.rb
class Song < ApplicationRecord
  #validations
  validates :nombre, presence: true 
  #relations
  belongs_to :album
  has_many :colaborations
  has_many :artists , through: :colaborations
end

app/models/state.rb
class State < ApplicationRecord
  #validations
  validates :nombre, presence: true 
  #relations
  has_many :artists , dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to artists_path}
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to artists_path}
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artist_params
      params.require(:artist).permit(:nombre, :descripcion, :informacion, :location_id, :state_id, :fecha_ini, :fecha_fin)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/core_helper.rb
module CoreHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_album.html.erb
<tr>
        <td><%= album.artist.nombre %></td>
        <td><%= album.album.nombre %></td>
        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/artists/_form.html.erb
<%= form_with(model: artist, local: true) do |form| %>
<% if artist.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

  <ul>
    <% artist.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group row">
  <%= form.label :nombre, :class => "col-sm-2 col-form-label" %>
  <%= form.text_field :nombre, :class =>"col-sm-5" %>

</div>

<div class="form-group row">
  <%= form.label :descripcion, :class => "col-sm-2 col-form-label" %>
  <%= form.text_field :descripcion, :class =>"col-sm-5" %>

</div>

<div class="form-group row">
  <%= form.label :informacion, :class => "col-sm-2 col-form-label" %>
  <%= form.text_field :informacion, :class => "col-sm-5" %>
 
</div>

<div class="form-group row">
  <%= form.label :Estado, :class => "col-sm-2 col-form-label" %>
  <%= form.collection_select(:state_id, State.all, :id, :nombre, {}, {:class => "col-sm-5 btn btn-secondary dropdown-toggle"})  %>
</div>

<div class="form-group row">

  <%= form.label "Fecha de inicio de actvividad", :class => "col-sm-2 col-form-label"%>
  <div class="col-sm-5">
  <%= form.date_field :fecha_ini, :class=> "date_picker" %>
  </div>
</div>

<div class="form-group row">
  <%= form.label "Fecha de Fin (Dejar en blanco si esta en activo)", :class => "col-sm-2 col-form-label"%>
  <div class="col-sm-5">

    <%= form.date_field :fecha_fin, :class=> "date_picker"  %>
  </div>
</div>



<%= form.hidden_field :location_id, :value => "2"%>
<%= form.submit nil, :class => "btn btn-primary" %>

<% end %>

app/views/artists/_formAlbums.html.erb
<%= form_with(model: artist, local: true) do |form| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist_album from being saved:</h2>

      <ul>
        <% artist.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group row">
  <%= form.label :nombre, :class => "col-sm-2 col-form-label" %>
  <%= form.text_field :nombre, :class =>"col-sm-5" %>

</div>

<div class="form-group row">
  <%= form.label :descripcion, :class => "col-sm-2 col-form-label" %>
  <%= form.text_field :descripcion, :class =>"col-sm-5" %>

</div>

<div class="form-group row">
  <%= form.label :informacion, :class => "col-sm-2 col-form-label" %>
  <%= form.text_field :informacion, :class => "col-sm-5" %>
 
</div>

<div class="form-group row">
  <%= form.label :Estado, :class => "col-sm-2 col-form-label" %>
  <%= form.collection_select(:state_id, State.all, :id, :nombre, {}, {:class => "col-sm-5 btn btn-secondary dropdown-toggle"})  %>
</div>

<div class="form-group row">

  <%= form.label "Fecha de inicio de actvividad", :class => "col-sm-2 col-form-label"%>
  <div class="col-sm-5">
  <%= form.date_field :fecha_ini, :class=> "date_picker" %>
  </div>
</div>

<div class="form-group row">
  <%= form.label "Fecha de Fin (Dejar en blanco si esta en activo)", :class => "col-sm-2 col-form-label"%>
  <div class="col-sm-5">

    <%= form.date_field :fecha_fin, :class=> "date_picker"  %>
  </div>
</div>



<%= form.hidden_field :location_id, :value => "2"%>

<table id ="genres" class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Artista</th>
      <th>Album</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <%= render partial: "album", collection: @artist.albums%>

  </tbody>
</table>
<br>
<h2>Añadir álbum al artista</h2>
<div class="fields">
	<%=form.label "Género"%>
	<%= form.collection_select(:album_id, Album.all, :id, :nombre) %>
</div>
 	<%= form.hidden_field :artist_id, :value => params[:artist_id]%>
<div class="actions" id="submit">
    <%= form.submit %>
</div>
<%end%>

app/views/artists/add_albums.html.erb
<%= render 'formAlbums', artist_album: @artist_albums %>
<%= link_to 'Back',{controller: "artists", action: "index"}, :class => "btn btn-primary" %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'formAlbums', artist: @artist %>



<%= link_to 'Show', @artist, :class => "btn btn-primary" %> 
<%= link_to 'Back', artists_path, :class => "btn btn-primary" %> 

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Artistas</h1>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Estado</th>
      <th>Fecha de Inicio</th>
      <th>Fecha de fin</th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.nombre %></td>
        <td><%= artist.descripcion %></td>
        <td><%= artist.state.nombre %></td>
        <td><%= artist.fecha_ini %></td>
        <td>
        <% if artist.fecha_fin.nil? %>
          Actualidad
        <%else%>
          <%= artist.fecha_fin %>
        <%end%>
        </td>
        <td><%= link_to 'Ver', artist %></td>
        <td><%= link_to 'Editar', edit_artist_path(artist) %></td>
        <td><%= link_to 'Eliminar', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Añadir géneros', {controller: "genre_artists", action: "add_genres", artist_id: artist.id}%></td>
        <td><%= link_to 'Añadir álbumes', {controller: "artists_albums", action: "add_albums", artist_id: artist.id}%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Añadir Artista', new_artist_path, :class => "btn btn-primary" %>
<%= link_to 'Crear Album', new_album_path, :class => "btn btn-primary" %>

app/views/artists/new.html.erb
<h1>Nuevo Artista</h1>

<%= render 'form', artist: @artist %>
<br>


<%= link_to 'Back', artists_path, :class => "btn btn-primary"  %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @artist.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @artist.descripcion %>
</p>

<p>
  <strong>Informacion:</strong>
  <%= @artist.informacion %>
</p>

<p>
  <strong>Location:</strong>
  <%= @artist.location_id %>
</p>

<p>
  <strong>State:</strong>
  <%= @artist.state_id %>
</p>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>