config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :generates
  resources :states
  resources :countries
  resources :provinces
  resources :cities
  resources :locations
  resources :genres
  resources :albums
  resources :songs
  resources :artists
  resources :genre_artists
  resources :album_types
  resources :artist_albums
  post 'core/:song_id', to: 'core#show', as: 'core_path'
  get '/main_page/', to: 'main_page#index', as: 'main_page_path'
  get '/genre_artists/:artist_id/add_genres', to: 'genre_artists#add_genres'
  post '/genre_artists/add_genres', to: 'genre_artists#create'
  get '/artists_albums/:artist_id/add_albums', to: 'artists_albums#add_albums'
  post '/artists_albums/add_albums', to: 'artists_albums#create'
  get '/songs/:album_id/add_genres', to: 'songs#add_songs', as: 'add_songs_path'  
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :album_type
  has_and_belongs_to_many :artists
  has_many :songs , dependent: :destroy
  has_many :artist_albums
  has_many :artist , through: :artist_albums
  has_many :genre_albums
  has_many :genres, through: :genre_albums
end

app/models/album_artist.rb
class AlbumArtist < ApplicationRecord
  belongs_to :artist_id
  belongs_to :album_id
end

app/models/album_type.rb
class AlbumType < ApplicationRecord
end

app/models/artist.rb
class Artist < ApplicationRecord
  #validations
  validates :nombre, presence: true
  validates :descripcion, presence: true

  #relations
  belongs_to :location
  belongs_to :state
  has_and_belongs_to_many :albums
  has_many :genre_artists , dependent: :destroy
  has_many :genres , through: :genre_artists, dependent: :destroy
  has_many :songs , through: :albums, dependent: :destroy
end

app/models/city.rb
class City < ApplicationRecord
  #validations
  validates :nombre, presence: true 
  #relations
  belongs_to :province
  has_many :locations , dependent: :destroy

end

app/models/colaboration.rb
class Colaboration < ApplicationRecord
  #validations
  validates :artist_id, presence: true
  validates :song_id, presence: true
  #relations
  belongs_to :artist
  belongs_to :song
end

app/models/country.rb
class Country < ApplicationRecord
	#Validations
	validates :nombre , presence: true
	#Relations
	has_many :provinces , dependent: :destroy
	has_many :locations , dependent: :destroy
end

app/models/generate.rb
class Generate < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
	#validations
  	validates :nombre, presence: true 
  	#relations
	has_many :genre_artists
	has_many :artists ,through: :genre_artists
	has_many :genre_albums
	has_many :albums ,through: :genre_albums
end

app/models/genre_album.rb
class GenreAlbum < ApplicationRecord
  validates :genre_id, presence: true
  validates :album_id, presence: true

  belongs_to :genre
  belongs_to :album
end

app/models/genre_artist.rb
class GenreArtist < ApplicationRecord
  validates :artist_id, presence: true
  validates :genre_id, presence: true

  belongs_to :artist
  belongs_to :genre
end

app/models/location.rb
class Location < ApplicationRecord
  validates :city_id, presence: true
  validates :province_id, presence: true
  validates :country_id, presence: true

  belongs_to :city
  belongs_to :province
  belongs_to :country
end

app/models/province.rb
class Province < ApplicationRecord
  #validations
  validates :nombre, presence: true 
  #relations
  belongs_to :country
  has_many :cities , dependent: :destroy

end

app/models/song.rb
class Song < ApplicationRecord
  #validations
  validates :nombre, presence: true 
  #relations
  belongs_to :album
  has_many :colaborations
  has_many :artists , through: :colaborations
end

app/models/state.rb
class State < ApplicationRecord
  #validations
  validates :nombre, presence: true 
  #relations
  has_many :artists , dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_back(fallback_location: root_path) }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_back(fallback_location: root_path) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def state_params
      params.require(:state).permit(:nombre)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/core_helper.rb
module CoreHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.erb
<%= form_with(model: state, local: true) do |form| %>
  <% if state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
        <% state.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing State</h1>

<%= render 'form', state: @state %>

<%= link_to 'Show', @state, :class => "btn btn-primary" %>  %> |
<%= link_to 'Back', states_path, :class => "btn btn-primary" %>  %>

app/views/states/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Estados</h1>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= state.nombre %></td>
        <td><%= link_to 'Show', state %></td>
        <td><%= link_to 'Edit', edit_state_path(state) %></td>
        <td><%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Nuevo estado', new_state_path, :class => "btn btn-primary"  %>
<%= link_to 'Atrás', url_for(:back), :class => "btn btn-primary"  %>

app/views/states/new.html.erb
<h1>New State</h1>

<%= render 'form', state: @state %>

<%= link_to 'Back', states_path, :class => "btn btn-primary"  %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @state.nombre %>
</p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>