config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :generates
  resources :states
  resources :countries
  resources :provinces
  resources :cities
  resources :locations
  resources :genres
  resources :albums
  resources :songs
  resources :artists
  resources :genre_artists
  resources :album_types
  resources :artist_albums
  post 'core/:song_id', to: 'core#show', as: 'core_path'
  get '/main_page/', to: 'main_page#index', as: 'main_page_path'
  get '/genre_artists/:artist_id/add_genres', to: 'genre_artists#add_genres'
  post '/genre_artists/add_genres', to: 'genre_artists#create'
  get '/artists_albums/:artist_id/add_albums', to: 'artists_albums#add_albums'
  post '/artists_albums/add_albums', to: 'artists_albums#create'
  get '/songs/:album_id/add_genres', to: 'songs#add_songs', as: 'add_songs_path'  
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :album_type
  has_and_belongs_to_many :artists
  has_many :songs , dependent: :destroy
  has_many :artist_albums
  has_many :artist , through: :artist_albums
  has_many :genre_albums
  has_many :genres, through: :genre_albums
end

app/models/album_artist.rb
class AlbumArtist < ApplicationRecord
  belongs_to :artist_id
  belongs_to :album_id
end

app/models/album_type.rb
class AlbumType < ApplicationRecord
end

app/models/artist.rb
class Artist < ApplicationRecord
  #validations
  validates :nombre, presence: true
  validates :descripcion, presence: true

  #relations
  belongs_to :location
  belongs_to :state
  has_and_belongs_to_many :albums
  has_many :genre_artists , dependent: :destroy
  has_many :genres , through: :genre_artists, dependent: :destroy
  has_many :songs , through: :albums, dependent: :destroy
end

app/models/city.rb
class City < ApplicationRecord
  #validations
  validates :nombre, presence: true 
  #relations
  belongs_to :province
  has_many :locations , dependent: :destroy

end

app/models/colaboration.rb
class Colaboration < ApplicationRecord
  #validations
  validates :artist_id, presence: true
  validates :song_id, presence: true
  #relations
  belongs_to :artist
  belongs_to :song
end

app/models/country.rb
class Country < ApplicationRecord
	#Validations
	validates :nombre , presence: true
	#Relations
	has_many :provinces , dependent: :destroy
	has_many :locations , dependent: :destroy
end

app/models/generate.rb
class Generate < ApplicationRecord
end

app/models/genre.rb
class Genre < ApplicationRecord
	#validations
  	validates :nombre, presence: true 
  	#relations
	has_many :genre_artists
	has_many :artists ,through: :genre_artists
	has_many :genre_albums
	has_many :albums ,through: :genre_albums
end

app/models/genre_album.rb
class GenreAlbum < ApplicationRecord
  validates :genre_id, presence: true
  validates :album_id, presence: true

  belongs_to :genre
  belongs_to :album
end

app/models/genre_artist.rb
class GenreArtist < ApplicationRecord
  validates :artist_id, presence: true
  validates :genre_id, presence: true

  belongs_to :artist
  belongs_to :genre
end

app/models/location.rb
class Location < ApplicationRecord
  validates :city_id, presence: true
  validates :province_id, presence: true
  validates :country_id, presence: true

  belongs_to :city
  belongs_to :province
  belongs_to :country
end

app/models/province.rb
class Province < ApplicationRecord
  #validations
  validates :nombre, presence: true 
  #relations
  belongs_to :country
  has_many :cities , dependent: :destroy

end

app/models/song.rb
class Song < ApplicationRecord
  #validations
  validates :nombre, presence: true 
  #relations
  belongs_to :album
  has_many :colaborations
  has_many :artists , through: :colaborations
end

app/models/state.rb
class State < ApplicationRecord
  #validations
  validates :nombre, presence: true 
  #relations
  has_many :artists , dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController

	def index
		@artists = Artist.all()
		@albums = Album.all()
		@songs = Song.all()
	end	


end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/core_helper.rb
module CoreHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/main_page/_album.html.erb
<div class="col-sm-3 ">
	<div class="card" id="band_card">
		<div class="mx-auto"> 
			<img class="card-img-top" src="..." alt="Card image cap">
			<div class="card-body">
				<h5 class="card-title"><%= album.nombre%></h5>
				<p class="card-text"><%= album.descripcion%></p>
				<%= link_to 'Ver más', album_path(album), :class => "btn btn-primary"%> 
			</div>
		</div>
	</div>
</div>

app/views/main_page/_artist.html.erb
<div class="col-sm-3 ">
	<div class="card" id="band_card">
		<div class="mx-auto"> 
			<img class="card-img-top" src="..." alt="Card image cap">
			<div class="card-body">
				<h5 class="card-title"><%= artist.nombre%></h5>
				<p class="card-text"><%= artist.descripcion%></p>
				<%= link_to 'Ver más', artist_path(artist), :class => "btn btn-primary"%>
			</div>
		</div>
	</div>
</div>

app/views/main_page/_song.html.erb
<div class="col-sm-3 ">
	<div class="card" id="band_card">
		<div class="mx-auto"> 
			<img class="card-img-top" src="..." alt="Card image cap">
			<div class="card-body">
				<h5 class="card-title"><%= song.nombre%></h5>
				<p class="card-text"><%= song.album.nombre%></p>
				<%= form_tag (core_path_url :method => "show", :song_id => song.id)do %>
					<%= label_tag(:q, "Palabra a buscar") %>
					<%= text_field_tag(:q) %>
				 	<%= submit_tag :ir %>
				<% end %>


			</div>
		</div>
	</div>
</div>

app/views/main_page/index.html.erb
 <div class="container">
 	<h3>Bienvenido <%= current_user.email%></h3>

 	<h4>Últimas bandas añadidas</h4>
 	<div class="row">
 		<%= render partial: "artist", collection: @artists %>
 	</div>


 	<h4>Últimos álbumes</h4>
 	<div class="row">
 		<%= render partial: "album", collection: @albums %>
 	</div>

 	<h5>Últimas canciones</h4>
 	<div class="row">
 		<%= render partial: "song", collection: @songs %>
 	</div>

 </div>